### ISSUE TITLE
reproducible build for wallet fails b/c APK is built from newer commit than tag

### ISSUE THREAD

**Issue by obfusk** [admin-ch/CovidCertificate-App-Android#111]
`wallet-prod-1.0.0-1001-signed.apk` is clearly not built from tag `v1.0.0-versionCode-1001-wallet`, but from later commit 8b31f3e8d06125f591e7eb4204191c21edfe0b79 instead.

**Comment by goebelUB** [comment]
Thanks a lot, I've changed the tag and the Github release to point to the correct commit.
