### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by davidgfnet** [admin-ch/CovidCertificate-App-Android#122]
Since yesterday's update the app crashes right after opening. It does render the UI but immediately crashes.
Got a shot from the local logcat, seems related to the local encrypted storage.

Attaching a screenshot with the backtrace.

![Screenshot_20210620-111537_Terminal_Emulator.png](https://user-images.githubusercontent.com/3145339/122668733-c50c3a80-d1b9-11eb-9cbe-259d84332c0c.png)

**Comment by goebelUB** [comment]
Does this persists for you in v1.2.1?

**Comment by davidgfnet** [comment]
Fixed!
Awesome work!
