### ISSUE TITLE
Scanning of real certificate is not possible after scanning a fake code

### ISSUE THREAD

**Issue by dominikponniah** [admin-ch/CovidCertificate-App-Android#164]
Since the Fix in Issue #74 the App does not slow down at all, but the new problem is the following:

1. I open the Swiss-Covid-App
2. I tap on "+"
3. I select the QR-Code option
4. I scan a random QR-Code found in here: https://duckduckgo.com/?q=sample+qr+code&iar=images&iax=images&ia=images
5. The App shows, that the scanned code is not valid
6. I use my personal QR-Code and try to scan it
7. The App does not show the Certificate-Details

When i leave the scanner and re-enter it again to scan my certificate directly, my personal data is shown correctly.

**Comment by goebelUB** [comment]
Thanks a lot for the nice step-by-step report, this is now fixed on main.
