### ISSUE TITLE
Bold font in titles in covid certificate page

### ISSUE THREAD

**Issue by xzyaoi** [admin-ch/CovidCertificate-App-Android#204]
Hi,

In the covid certificate page (after clicking the QR code and scroll down a bit), I found the order of the text is a bit weird. It is like 

```
2/2
**Dose**
```

I am not sure if it is intended, or it should be like:

```
**Dose**
2/2
```

Thanks in advance!

**Comment by goebelUB** [comment]
Thanks for your feedback, I passed it on to our team.
This is an explicit design decision, so it won't change in the near future.
