### ISSUE TITLE
[Feature Request] Textual Input for dedicated qr scanner

### ISSUE THREAD

**Issue by TeoGoddet** [admin-ch/CovidCertificate-App-Android#231]
Hi ! 
Some dedicated android qr scanner (such as data logic memor 10) provide qr data as text input 
It would be nice if the verifier app was compatible with this to allow quick scan.

thanks, 
Téo

**Comment by jeffallen** [comment]
At the Locarno Festival I saw hundreds of check-ins and QR code scanning wasn't a pain.

Remember that a QR code is not valid without photo id. Making the scanning faster does not change the speed of the line, that's more about how efficiently the certificate holder can show their ID card and the verifier can check the name and then check the photo. After a few check-ins, people get efficient at it, having the QR code up, then presenting the id next to their face.

**Comment by staubix** [comment]
Hey jeffallen, thanks for your reply. 

Of course it makes the line faster. It's already a lot faster when I use my rather new iPhone compared to some older/cheap android phones. My colleagues sometimes needed 10s or more to check one qr code. But even with my iPhone 12 pro it was difficult sometimes.

**Comment by goebelUB** [comment]
v2.6.0 includes support for external scanners, including from Zebra. Does this cover you or are there other devices that you need support for?

**Comment by staubix** [comment]
@goebelUB Yes. Thanks a lot! This is going to be quite a game changer for nightlife. Now the only suboptimal thing is that I have to scroll down to see the date of birth hence the screen format of the zebra computers.

Despite of that I'm quite happy now!

https://user-images.githubusercontent.com/89586892/135989955-c45df7bd-f5cd-4ead-983e-e90b0ce79f2c.MOV

.
