### ISSUE TITLE
Align download Huawei download button and use other style

### ISSUE THREAD

**Issue by aha999** [admin-ch/CovidCertificate-App-Android#248]
Huawei downlaod button on the Readme.md is misaligned and is not using the same style as the Google Play and F-Droid (white edges).

Here you can find the correct button with the same style and sources for the button: https://github.com/aha999/DownloadButtons/#huawei-appgallery

![image](https://user-images.githubusercontent.com/50620416/130871015-f4450c7c-c35f-4874-a024-108853a6ad4e.png)

**Comment by sashpawar11** [comment]
Hey, I fixed it. The problem was with the first two badges - they had extra padding around them, so I modified the huwaei badge to have the same size and padding around it and it worked! I will make a PR.
