### ISSUE TITLE
Use regular QR code pattern for Covid certificate light

### ISSUE THREAD

**Issue by g4b1nagy** [admin-ch/CovidCertificate-App-Android#251]
The Covid certificate light uses a different type of QR code pattern, with smaller dots, making it harder for devices to read. You need better lighting conditions and less movement. I think it would be a good idea if Covid certificate light would use the standard QR code pattern as well and use a different indicator to distinguish itself from the regular Covid certificate.

**Comment by doerig** [comment]
We use a Datalogic Gryphon 2D Barcode scanner to read the QR Code. It works for the normal certificate, but light certificates cannot be read. We would also appreciate if the standard pattern is used.
