### ISSUE TITLE
Sort certificates by validity

### ISSUE THREAD

**Issue by barmettlerl** [admin-ch/CovidCertificate-App-Android#273]
It would be a bit more user friendly if the valid certificates are shown first and the expired ones at last. I tested me once after my vaccination and now I have to scroll to the right each time I need to show the certificate.

**Comment by goebelUB** [comment]
If you have multiple certificates, there is a button at the bottom of the home page that brings you to a compact list of certs. You can reorder them there, and the order will be reflected on the home screen.
