### ISSUE TITLE
Doesn't have a valid signature?

### ISSUE THREAD

**Issue by BarisGURENC** [admin-ch/CovidCertificate-App-Android#275]
Hi,

At my build,  I get "The COVID certificate does not have a valid signature" message on the result screen.

Same QR Code, but there is no that kind of alert/error message on the official android app.

**Comment by BarisGURENC** [comment]
@goebelUB , @benz-ubique 
Is there a point I missed?

**Comment by goebelUB** [comment]
We need more information, otherwise it's hard to tell what is going wrong. E.g. what error code do you get (e.g. G|NWF)?
Since you are building it yourself, you could build the debug flavour (`./gradlew wallet:assembleProdDebug`) to get extra log output. Also make sure you are also building the prod flavour, since the dev and abn flavours use different signing keys against which certs are checked.

**Comment by BarisGURENC** [comment]
> We need more information, otherwise it's hard to tell what is going wrong. E.g. what error code do you get (e.g. G|NWF)?
> Since you are building it yourself, you could build the debug flavour (`./gradlew wallet:assembleProdDebug`) to get extra log output. Also make sure you are also building the prod flavour, since the dev and abn flavours use different signing keys against which certs are checked.

Actually i don't get error on Android Studio.
My apk doesn't verify the informations which i got from QR. But Official APP does.
Please check the linked image : https://ibb.co/NYnB79K

**Comment by goebelUB** [comment]
How did you build your app? Opened it in Android Studio and hit "run"?
If you click on the (i) in the top right and scroll down, what does it say here? Does it say "prod"?
<img src=https://user-images.githubusercontent.com/56064810/134932799-54c707a2-7fbd-49c4-87c3-736748e9fb63.jpeg width=300px>

**Comment by kairos34** [comment]
I had similar problem and noticed that if "certificates.json" is not up to date, it says certificate does not have valid signature. Verifier app tries to update trustlist files every time the main activity is resumed. I am gonna put **onCompletionCallback** and **onErrorCallback** to see what is happening when **_refreshTrustList()_** function called.
