### ISSUE TITLE
Standardized name not displayed in wallet

### ISSUE THREAD

**Issue by ofek-b** [admin-ch/CovidCertificate-App-Android#289]
Some countries that use different alphabets issue EU-conform QR-codes, and store both native ("name" field) and Latin ("standardized name" field) script on the QR-code. The app only uses the "name" field, making it practically unusable for people vaccinated in those countries, at least in checks where they only read the text (and don't scan the code). It would be really helpful if the standardized name will be used, at least in cases where the name is in a different alphabet.

~See screenshot below.~ If you scan the code with the Robert-Koch app, it shows the standardized name as one of the fields (though still only the normal name at the title...):

Thanks!

**Comment by goebelUB** [comment]
Thanks, we'll take this up as a potential (though currently low-priority) feature. It'll also have to go through the design department first.

<details>
<summary> about your screenshot (collapsed) </summary>
I took the liberty to edit and delete the screenshot from your message - no need to post personal QR codes here  :)
You should be able to delete your original comment by clicking on the edit history to fully remove the screenshot.
Right now it's still there, but at least not as much attention-grabbing anymore.
</details>
