### ISSUE TITLE
Forged Certificate gets validated

### ISSUE THREAD

**Issue by denysvitali** [admin-ch/CovidCertificate-App-Android#306]
Due to a bug in the QR decoder, forged QR Certificates get validated.  
  
This bug is similar (if not equal) to ministero-salute/it-dgc-verificaC19-android#185 and it can be reproduced as follows.

## Valid Certificate

![QR Valid](https://raw.githubusercontent.com/denysvitali/covid-cert-analysis/master/samples/saaaanchez.png)

![IMG_20211104_201430_883.jpg](https://user-images.githubusercontent.com/4939519/140405059-802f94fc-31fa-43d9-ba6f-369cd09c08d7.jpg)

This QR code has the same data as the one below. Sadly it gets validated in the Swiss Covid Checker app.

## Invalid Certificate

![Invalid QR](https://github.com/denysvitali/covid-cert-analysis/blob/295b839536cc6c82162ec908fb17ca3147c592db/samples/saaaanchez.png?raw=true)

Note that, when decoded with `zbar`, both QR codes have the same data contained.  
  
## Hypothesis

This feels like a QR Decoding issue. We're discussing it at denysvitali/covid-cert-analysis#9 and at ministero-salute/it-dgc-verificaC19-android#185

**Comment by goebelUB** [comment]
Thanks for reporting, we'll look into it!

**Comment by ubamrein** [comment]
About the first QR code passing:
It looks like this QR code has indeed a valid signature and might be maliciously issued, was a mistake during issuance or maybe was a test-case for the production system. In any case, I think we are safe to assume that this QR code should not be valid and so like Micky Mouse & Co this should be revoked in Switzerland soon. Thanks for collecting all of those!
 
About the encoding issue in the second QR code:
I'm using this tool [here](https://hcert-viewer.s3.eu-central-1.amazonaws.com/index.html ) to debug certificates (based on the Rust implementation found [here](https://github.com/ubamrein/dcc-playground/tree/main/web/dgc-web) ). As far as I can see the invalid QR-Code has a newline at the very end. Hence the two codes do not contain exactly the same data!
 
This is probably also why decoding (and hence verification) of the second QR code fails with the "D|B45" error -- '\n' is not a valid base45 character.

**Comment by denysvitali** [comment]
Oh, you're right, that could very much be the case since I strip newlines in my reader. Duh!

**Comment by denysvitali** [comment]
Maybe this is a wrong report. I just realized this QR is supposed to be valid and it's part of eu-digital-green-certificates/dcc-quality-assurance and it's thus supposed to be valid. It's just a weird certificate.  
  
I guess we can close this issue, sorry!

https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/main/AD/1.0.0/VAC-1-Pauta_Completa.png

**Comment by ubamrein** [comment]
No worries and thanks for your efforts!
