### ISSUE TITLE
Display if a person conforms to 2G (Recovered / Vaccinated)

### ISSUE THREAD

**Issue by simonerni** [admin-ch/CovidCertificate-App-Android#343]
> Alle öffentlichen Einrichtungen mit Zertifikatspflicht sowie alle Veranstaltungen innen und aussen haben zudem die Möglichkeit, den Zutritt auf geimpfte und genesene Personen (2G) zu beschränken und auf eine Maskenpflicht zu verzichten.

Without such an indicator in the Check App, this rule is un-enforcable.

**Comment by goebelUB** [comment]
Further down from [the same article](https://www.bag.admin.ch/bag/de/home/das-bag/aktuell/medienmitteilungen.msg-id-86260.html):

> Zu diesem Zweck muss die Prüf-App für die Covid-Zertifikate erweitert werden. Diese Anpassung wird erst per 13. Dezember 2021 zur Verfügung stehen. Bis dann müssen die Betreiber der Einrichtungen oder die Veranstalter manuell prüfen, ob die entsprechende Person geimpft oder genesenen ist.

**Comment by panmau** [comment]
> Bis dann müssen die Betreiber der Einrichtungen oder die Veranstalter manuell prüfen, ob die entsprechende Person geimpft oder genesenen ist.

In what way should that be manually checked until this is done?

**Comment by simonerni** [comment]
Thanks @goebelUB for the clarification! Missed that paragraph about the date.

It would be excellent if the Light Certificate would support the 2G indicator as well.

**Comment by goebelUB** [comment]
Version 3.0.0 is being rolled out now and includes this feature.
