### ISSUE TITLE
CoviDCertificate-App-Android 3.0 

### ISSUE THREAD

**Issue by agmmobile** [admin-ch/CovidCertificate-App-Android#359]
CovidCertificate.APP
![CovidAPP_3 0-3000000 Wallet](https://user-images.githubusercontent.com/59500111/145563728-a45a724b-7abd-4dbc-84ea-fec0d3cffe49.jpeg)
-Android Version 3.0 (3000000 Wallet ) Status cannot be determined during the check. the QR code turns orange and the question mark appears. Device: Android 8.1.0 display inch 2.4

**Comment by goebelUB** [comment]
3.0.0 is marked as a pre-release. There have been some API changes to the backend that have not yet been deployed to production.
Please try again on Monday when 3.0.0 is officially released.

**Comment by agmmobile** [comment]
Besten Dank, Wir werden die APP vorinstallieren lassen bevor das Gerät auf dem Markt kommt ende Dez. 21 (Tastaturhandy mit symple Android  )

**Comment by goebelUB** [comment]
Please still check again on Monday! There are already some additional bug fixes [on the release branch](https://github.com/admin-ch/CovidCertificate-App-Android/commits/release/version-3.0) that are not yet included in the currently uploaded APKs that were built yesterday.
Thus the APK as it is on Github now is still subject to change and does NOT resemble the final 3.0.0 release!

**Comment by goebelUB** [comment]
Version 3.0.0 is officially released now.
