### ISSUE TITLE
Booster after Johnson&Johnson does not reset duration

### ISSUE THREAD

**Issue by HarriOrri** [admin-ch/CovidCertificate-App-Android#368]
Hi,

getting a booster shot (in my case of Pfizer) after one dose of J&J single dose vaccine does not reset the duration to 1 year after the booster. However, a booster after 2 shots of AZ, Pfizer, Moderna and etc. giving a total of 3 shots does reset the duration to one year after the booster.

As far as I know, getting a booster shot in Switzerland resets the duration to 1 year after it, but I couldn't find anything about getting a booster shot after the J&J vaccine and the rules about the certificate duration.

The vaccination certificates which I used as reference (1x J&J and 1x Pfizer booster/2x AZ and 1x Moderna booster) are both from a foreign country but using the Covid Cert app. The J&J/Pfizer still has the duration as 365+21 days from the original dose of J&J while the AZ/Moderna has it now set as 364 days after the booster dose of Moderna.

**Comment by goebelUB** [comment]
Probably a validation rule issue, so let's keep the discussion in https://github.com/admin-ch/CovidCertificate-App-iOS/issues/271.

**Comment by HarriOrri** [comment]
Closed and moved to [admin-ch/CovidCertificate-App-iOS#271](https://github.com/admin-ch/CovidCertificate-App-Android/issues/368#issuecomment-997353544)
