### ISSUE TITLE
Info button 3G 2G 2G+ partially in intalian

### ISSUE THREAD

**Issue by jerem0808** [admin-ch/CovidCertificate-App-Android#378]
Hi,
When i click on the info button 3G 2G 2G+ i get only the 2G+ in italian (see below).
Samsung S21+
Android version 12
app version 3.2.0
Android
![image](https://user-images.githubusercontent.com/4958851/148792347-c5d57016-bb53-4b38-a556-5368bcb6c185.png)

**Comment by goebelUB** [comment]
Thanks a lot for the report! This should now be fixed server-side.
