### ISSUE TITLE
App compatible with Huawei 

### ISSUE THREAD

**Issue by markusg80** [admin-ch/CovidCertificate-App-Android#42]
Is this App compatible with Huawei HMS? Or is Google Service needed?

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Google services are not needed, this app has no proprietary dependencies (for now at least, I hope they don't add any..)

**Comment by markusg80** [comment]
This is great! It means that it is more trustful. On wich App Store will it be available? I saw something with f-droid?

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
Well, it will definitely be available in some form, at some point, on F-Droid. Now, the question is whether it will be in an official capacity (with the same name, possibly with reproducible builds, etc) or not. If the maintainers do not agree to inclusion, it will be published with a different name, etc (just like the contact tracing app: https://f-droid.org/packages/ch.corona.tracing/ )

However, as mentioned in issue #40, they seem to be amenable to the idea at least, so I am looking forward to working with the maintainers to have this FOSS app included on F-Droid :)

**Comment by goebelUB** [comment]
As mentioned, the app currently has no dependencies on GMS.

Furthermore, both apps are now available on the AppGallery:
- COVID Certificate: https://appgallery.huawei.com/#/app/C104434571
- COVID Certificate Check: https://appgallery.huawei.com/#/app/C104435637
