### ISSUE TITLE
Authentication for opening the app

### ISSUE THREAD

**Issue by informatik-bks** [admin-ch/CovidCertificate-App-Android#54]
Use fingerprint/biometric check to open the app, this helps to verify the owner of the cert.
As backup use code/password

**Comment by simonerni** [comment]
@informatik-bks What do you mean exactly when you state that it would help to verify the owner of the certificate?

I assume you mean it would help convince someone external checking the certificate, e.g. at an airport, that it is indeed your certificate that you present. In this case, the biometric check would add no more security, as the certficate is bound to the owner via inclusion of the name of the certificate holder.

Besides not adding security, it would also hinder usability, may not be used on devices without biometric sensors, and is trivially faked.

Please elaborate if I‘m misreading your suggestion.

**Comment by informatik-bks** [comment]
yes thats right, biometric was just idea.
