### ISSUE TITLE
Compiled Apk's for tests and debug

### ISSUE THREAD

**Issue by steveacab** [admin-ch/CovidCertificate-App-Android#59]
I compiled both WALLET AND VERIFIER apk's if anyone want to test, debug, control UX, text etc

https://github.com/steveacab/Verifier

The files are not signed and made from Android Studio.

**Comment by steveacab** [comment]
![Screenshot_20210602-161616](https://user-images.githubusercontent.com/4009959/120498194-565c6e00-c3bf-11eb-84f6-8a02be776acc.jpg)
![Screenshot_20210602-161633](https://user-images.githubusercontent.com/4009959/120498199-58263180-c3bf-11eb-85b7-3da20a2d333d.jpg)
![Screenshot_20210602-161647](https://user-images.githubusercontent.com/4009959/120498204-58263180-c3bf-11eb-824d-966c25b57765.jpg)

**Comment by informatik-bks** [comment]
Installation on Android 11 with One UI 3.1 works, okay its new but it works for both apps. Thanks for the packages

**Comment by goebelUB** [comment]
I'll close this, now that the apps are available on Google Play ([wallet](https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.wallet), [verifier](https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.verifier)).
