### ISSUE TITLE
Dump-Data for Testing

### ISSUE THREAD

**Issue by dominikponniah** [admin-ch/CovidCertificate-App-Android#69]
Are there any COVID-Certificates given to test the Functionalities of the QR-Codes and also its security?

This would also be helpful to check things up like the 'hackability' or encryption.

**Comment by goebelUB** [comment]
You can find QR codes for testing in [this repository](https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CH).
Note that these are signed with the keys from the DEV environment, so they should verify successfully on DEV builds, but not on PROD or ABN builds.
