### ISSUE TITLE
App slows Device down when scanning another QR-Code

### ISSUE THREAD

**Issue by dominikponniah** [admin-ch/CovidCertificate-App-Android#74]
While testing the Scanner-Function i experienced some big issues while scanning a simple QR-Code from other Webpages and Apps.

It seems like the App can't handle the data contained in the Code correctly. On my Main-Device (Huawei Mate 20 running Android 10) the App crashed and did also slow down my phone at all.

Maybe a stack-overflow?

**Comment by goebelUB** [comment]
Could you please elaborate?
"Crashed" as in you got a system dialog "COVID Certificate has stopped"?
How do you quantify "slow down my phone at all"? E.g. on my OnePlus 7, when I pull down the system status bar while scanning an invalid QR code, the camera preview (now partially in the background) might lag, but the pull-down-animation is still fluent (thus suggesting no global slowdown).

I know that the camera preview can hang for a split second when decoding an invalid code. Could your issue be just that, or is there more?

**Comment by dominikponniah** [comment]
Unfortunately, it is not as described by you on my test device. Since I often work with older devices, I have now also tested it with a Galaxy A7 (2018) and the Huawei device. On both, the app closes - I interpreted it as a crash - but the dialog appears (not on either device).

The crash occurred in 10 cases but only in 2 tests.

Regarding the camera, interacting with the device, i.e. dragging the status bar down or simply closing the app, slows down the entire smartphone process. As usual for Huawei, the camera does not respond very well in some cases, but it is also the case that the system animation slows down in the Samsung device. 

For me, these incidents were comparable to a simple browser overload on the web. Too many operations are performed or errors are detected so that the browser or the app does not work correctly anymore.

**Comment by dominikponniah** [comment]
@goebelUB as I tested it now with the Example-Codes you linked in Issue [#69](https://github.com/admin-ch/CovidCertificate-App-Android/issues/69). And it worked like in butter!

Both Devices recognized the Code and Display the Data correctly. Is I tried it again with other codes (also one from my Swiss Pass issued by SBB) it slowed down my device again...

**Comment by goebelUB** [comment]
The camera and QR scanning has been reworked in v2.0.0, which is now being rolled out. Please reopen if the issue persists.
