### ISSUE TITLE
Cannot find the app

### ISSUE THREAD

**Issue by steveacab** [admin-ch/CovidCertificate-App-Android#78]
A lot of comments on the Playstore say that the apps cannot be founded. And it's true. If you search "covid certificate" you can find only "swiss covid" app. Neither the wallet and the checker can be founded.

**Comment by chjohn22** [comment]
Search for "FOPH" (Federal Office of Public Health), both apps will show up in the search results.
The problem is that the names of both apps (COVID Certificate Check, COVID Certificate) consist of very generic words.

**Comment by steveacab** [comment]
I know, and i did it to install both. But that won't solve the problem for all of the people who want to install the apps.

**Comment by chjohn22** [comment]
Maybe the devs know of a way to tag the app or edit the description in the store, so that it gets indexed properly. A change of the apps name won't be feasible. At least print media and various guides do already explain to readers how to find it.

**Comment by steveacab** [comment]
A workaround it's never a good idea. A 70ish person will never do or understand that.

**Comment by goebelUB** [comment]
This is an issue on Google's side. Google is aware of it and is working on fixing it.

In the meantime, please use direct links.
Alternatively within the Play Store, you can hop via SwissCovid to the [FOPH page](https://play.google.com/store/apps/developer?id=Federal+Office+of+Public+Health+FOPH) that shows all apps published by the FOPH (including the COVID Certificate apps).

**Comment by steveacab** [comment]
> This is an issue on Google's side. Google is aware of it and is working on fixing it.
> 
> In the meantime, please use direct links.
> Alternatively within the Play Store, you can hop via SwissCovid to the [FOPH page](https://play.google.com/store/apps/developer?id=Federal+Office+of+Public+Health+FOPH) that shows all apps published by the FOPH (including the COVID Certificate apps).
> 

Well it's a 50/50. Maybe Swiss Covid certificate would had worked better. Btw I know that an app need time to be indexed, but those are official apps, so maybe if someone contact Google they can find a solution, because right now the only way to let the apps be downloaded is a paid campaign. This last one is highly recommend at the moment on those apps will be fast forgotten. 
I mean, guys, come on, there are a couple of Google's buildings in Zürich too.

**Comment by goebelUB** [comment]
Both apps should now be discoverable via search on Google Play.

**Comment by steveacab** [comment]
> Both apps should now be discoverable via search on Google Play.

Yes. Great.
