### ISSUE TITLE
Language of CovidCertApp should be changeable 

### ISSUE THREAD

**Issue by AdiWehrli** [admin-ch/CovidCertificate-App-Android#85]
The language of the app is set to the phone's default and cannot be changed. This could cause problems at borders/during voyages.

Language should be changeable by user.

**Comment by goebelUB** [comment]
The design of this feature is still under review.

Note that starting with the next release, if your system language (and hence the app) is in one of { DE, FR, IT, RM } then the items in the certificate details will have an additional label in English (the [iOS PR](https://github.com/admin-ch/CovidCertificate-App-iOS/pull/38) has some screenshots). This mirrors what you get on paper.

**Comment by goebelUB** [comment]
The option to change the language in-app will be in v2.4.0, scheduled to be officially released next week.
